### ISSUE TITLE
create a "Why Chlambase?" / About page

### ISSUE THREAD

**Issue by khybiske** [SuLab/ChlamBase.org#11]
I think the site needs a page that explains what chlambase is about, and briefly lists its unique features and advantages over other gene-based databases. Looks like wikigenomes has an 'About' section. Something like that... but maybe more feature-driven. I can imagine encouraging some colleagues to explore the site, and it's not immediately obvious what chlambase can do that other sites cannot.

**Comment by khybiske** [comment]
Another example: http://toxodb.org/toxo/showXmlDataContent.do?name=XmlQuestions.About

**Comment by andrewsu** [comment]
@khybiske want to take a crack at creating some text for this?

**Comment by khybiske** [comment]
Here is a first draft of some text:

**About ChlamBase**

ChlamBase, a fork of WikiGenomes, is an open source, user-curated database of functional annotations for 3 model Chlamydia species: C. trachomatis LGV L2, C. trachomatis D, and C. muridarum Nigg. A primary goal of this  portal is to provide a powerful user-oriented experience tailored to the research interests of the Chlamydia research community, and to the unique biology of Chlamydia. A central feature of ChlamBase is to allow users to view, add, and edit: 
- evidence-based gene annotations
- engineered mutant strains
- orthologous gene comparisons
- developmental gene expression
- host interaction targets

**WikiGenomes**

WikiGenomes is a portal to the biological content in the Wikidata project. It currently hosts the genes, proteins, and a variety of functional annotations for 120 bacteria genomes. WikiGenomes is designed to be both a resource for basic researchers to browse the collective knowledge of a variety of well studied organisms, and a technology layer that allows the user to add to that collective knowledge. To support this WikiGenomes provides defined editing forms that prompt the user to provide key information and references. WikiGenomes then adds that knowledge to the Wikidata knowledge graph.

**Publications**

For more information about WikiGenomes, the scaffold of ChlamBase, please refer to:

Putman TE, Lelong S, Bugstaller-Muehlbacher S, Waagmeester A, Diesh C, Dunn N, Munoz-Torres M, Stupp GS, Wu C, Su AI, Good BM.
WikiGenomes: an open web application for community consumption and curation of gene annotation data in Wikidata.
Database, 2017, PMMID 28365742

**Advisors**

Andrew Su (The Scripps Research Institute, USA)
Tim Putman (TBA)
Kevin Hybiske (University of Washington, USA)
Scott Hefty (University of Kansas, USA)
Daniel Rockey (Oregon State University, USA)
more!  ?

**Funding**

Support for ChlamBase comes NIH/NIGMS R01GM089820, PI Andrew Su.

**Version history**

**FAQ**

**Comment by putmantime** [comment]
Looks great Kevin.  I will add this to the landing page

**Comment by khybiske** [comment]
I feel like it should also remain accessible even after the user has drilled into a genome or gene. But not sure where it should go...

**Comment by putmantime** [comment]
That's a good idea.  I can create a persistent footer that is there on every page

**Comment by khybiske** [comment]
This is all done, right? The implementation looks great!

**Comment by putmantime** [comment]
Yes, forgot to tag this commit: 8cdb7f5c02f08cf907a8c9927cef1effde1c8de0.
Leaving open in case there are any suggested modifications
