### ISSUE TITLE
Add visualization of ortholog alignments

### ISSUE THREAD

**Issue by khybiske** [SuLab/ChlamBase.org#12]
A cool feature would be to (in the **Orthologs** window) add a button that triggers a script/webapp(?) that aligns the sequences listed (maybe checkboxes for user to choose). At worst, this is a BLAST. But surely there must be better web functions for this, like clustal...?

**Comment by andrewsu** [comment]
MUSCLE (multiple sequence alignment algorithm) has a REST web service here: http://www.ebi.ac.uk/Tools/webservices/services/msa/muscle_rest

nice little MSA viewer widget: http://msa.biojs.net/

stitching this all together might be a nice intern/rotation project...

**Comment by putmantime** [comment]
This looks great.  I will play a few example API calls and post results here.

**Comment by khybiske** [comment]
That's really neat (for aa sequences). For most other organisms in wikigenomes, aa alignments will be a great tool. Chlamydia is a little unique in that the DNA sequences across species are conserved, which is why we also are fond of gene alignments for orthologs.

**Comment by andrewsu** [comment]
both protein and nucleotide MSAs should be possible with MUSCLE and the biojs widget I think.  Unless you @khybiske saw something that says otherwise?

**Comment by khybiske** [comment]
You are right. I had only clicked their 'use it' button...

**Comment by putmantime** [comment]
I just did a nucleotide alignment:
http://www.ebi.ac.uk/Tools/services/web/toolresult.ebi?jobId=muscle-I20170714-190003-0316-2963421-oy
