### ISSUE TITLE
Loosen search and filtering to make "_" optional

### ISSUE THREAD

**Issue by djow2019** [SuLab/ChlamBase.org#150]

**Comment by djow2019** [comment]
Was also thinking of making the beginning 0's optional as well. So CTL0260 could also be found with CTL260.

Thoughts @khybiske ?

**Comment by khybiske** [comment]
Y E S ! (for all species)

**Comment by djow2019** [comment]
Done
![image.png](https://images.zenhubusercontent.com/5a6639ad4b5806bc2bc3ca25/27530dd8-70eb-49e6-b057-2d663cc0721d)
