### ISSUE TITLE
Add BLAST tool

### ISSUE THREAD

**Issue by khybiske** [SuLab/ChlamBase.org#157]
Suggested by Scott, and a good idea. In the Gene Product module, next to Download, make a column/button to send the user to NCBI BLAST(protein). Should be easy, right?

**Comment by djow2019** [comment]
Just a link to blastp? Sure

**Comment by djow2019** [comment]
Think its done
![image.png](https://images.zenhubusercontent.com/5a6639ad4b5806bc2bc3ca25/87938ef0-da11-4bf5-b666-c99a87f834dc)

**Comment by khybiske** [comment]
That's great. Just to explore the idea... do you think there's a way to link directly to a prefilled blastp query? Maybe that's not possible. Alternatively, copy AA sequence to clipboard and go to blastp: https://blast.ncbi.nlm.nih.gov/Blast.cgi?PROGRAM=blastp&PAGE_TYPE=BlastSearch&LINK_LOC=blasthome

**Comment by djow2019** [comment]
Those are both good ideas. I'll see if I can get the first one before I do the second one...

**Comment by djow2019** [comment]
Updated with the former. live now

**Comment by khybiske** [comment]
All done, right?
