### ISSUE TITLE
improve ortholog data

### ISSUE THREAD

**Issue by putmantime** [SuLab/ChlamBase.org#19]
A joint effort has been discussed to create a robust ortholog table that includes evidence

**Comment by putmantime** [comment]
example data model:

**Comment by andrewsu** [comment]
per discussion with @khybiske, we want to set up a hybrid computational-manual pipeline to define orthologs.  Initial criteria would include:

* % sequence similarity
* synteny
* reciprocal best match

Next step will be for Kevin to propose thresholds/groups based on the above criteria.  Basic goal is to identify ortholog assignments that need manual curation.

**Comment by khybiske** [comment]
@andrewsu After some discussion and thought, we hopefully have some directions to pursue. The criteria for defining orthologous genes between Chlamydia species/strains should be what you listed above. 

For assigning arbitrary thresholds, I might go with the following (all orthologs should share synteny and reciprocal matching):
- Very high confidence (>90% sequence identity)
- High confidence (>50% sequence identity)
- Requires manual analysis (we do it by hand)

Ideally, it would be nice if the site reports to the user the % identity along with the categorical assignment. This would allow the user to additionally define what thresholds are important to her/him (e.g., >98%). We know of a couple of instances in which a gene is severely truncated in one species vs another, but this will emerge with 'manual analysis'.

Helpful?

**Comment by andrewsu** [comment]
I think the criteria the define reciprocal best match are clear, but how about for synteny?  Seems like a fuzzier concept to me. Thoughts on how to make that an easily computable metric?

**Comment by khybiske** [comment]
I don't know how easy it is to computationally assess synteny. At its simplest, it would be that the genes before and after the one in question are the 'same' (homologous). Perhaps not that easy to implement... 

For Chlamydia, we likely don't have to deal with synteny since nearly all of the genes across species are in synteny. I am almost certain that if we scrub a genome and find genes that aren't, they will also have poor/zero sequence similarity. Seq ID is going to be our best variable that defines orthologs.

We can probably punt on syteny algorithms until you choose to tackle other microbes.

**Comment by andrewsu** [comment]
got it...  okay, two last questions (which I think we covered in our last phone call, but I forget). Was this something that we were going to tackle on our end, or something that one of your labs was going to do?  And is this a must-have for the first paper, or a nice-to-have (that maybe we incorporate on revisions)?

**Comment by khybiske** [comment]
I think you guys were maybe going to tackle the initial ortholog assignments, computationally (someone new who joined?). The manual analysis will then be done by us, for all ambiguous genes.

Is it a must have.... probably not. The existing ortholog module already constitutes a feature that no other general databases possess. What we are discussing is just a significant enhancement.

**Comment by andrewsu** [comment]
given @djow2019's initial work performing the computational analysis, @khybiske's subsequent review, @putmantime's work posting [the resulting file on figshare](https://figshare.com/articles/Chlamydial_Ortholog_Mappings/5866950/1) and updating wikidata, and then @djow2019's work to update the website to use those data (I think in this commit 5fd0fd0c1b3778f11e7f6b90bd0c6c7c91b43a37), I think this issue can be closed.
