### ISSUE TITLE
Site name

### ISSUE THREAD

**Issue by khybiske** [SuLab/ChlamBase.org#23]
Not really an "issue".

Keep as ChlamBase.org or change? Worthy of a discussion.. Most related portals seem to use ___base or ___db, so both ChlamBase or ChlamDB are appopriate. The chlamdb.org domain is also available. ChlamydiaBase and ChlamydiaDB are not as good – needlessly long. Any better ideas?

**Comment by andrewsu** [comment]
after letting this one percolate for nine months, going to close this issue.  We've used "chlambase" enough in posters, talks, and abstracts that I think it would tough to change at this point...
