### ISSUE TITLE
create a chlambase icon

### ISSUE THREAD

**Issue by andrewsu** [SuLab/ChlamBase.org#24]
Perhaps something based on one of these images? 
https://www.google.com/search?q=chlamydia+pathogen&tbm=isch

If @putmantime and @khybiske can agree on one or a few representative images, we can get a graphics person to make it into a proper icon...

**Comment by khybiske** [comment]
If for the site itself (header etc), I'd rather draw something (frankly I'm pretty good at it). All of 'stock imagery' are either inaccurate or bad. 

If for a favicon, that's less my expertise.

**Comment by andrewsu** [comment]
@khybiske just waiting for you to accept the invitation to be a collaborator so I can assign this issue to you... ;)

**Comment by khybiske** [comment]
@andrewsu Done, I think.

**Comment by khybiske** [comment]
I whipped up a possible new header logo for us to use. Take a look and comment on: whether you like it, alternative suggestions for me to try, and which typeface if you do like it. This is not meant to replace the splash page graphic, but rather to appear on every gene entry page. 

I also included a sample favicon.

![chlambase headers](https://user-images.githubusercontent.com/29986637/39211461-7e183b5a-47c0-11e8-947d-008c7d497614.png)

**Comment by khybiske** [comment]
@andrewsu I'll let you rally the troops to view and comment.

**Comment by khybiske** [comment]
Favicons:

![favicon-16x16](https://user-images.githubusercontent.com/29986637/39211619-0c1c3dde-47c1-11e8-8628-1a0c73158e11.png)
![favicon-32x32](https://user-images.githubusercontent.com/29986637/39211620-0c31d216-47c1-11e8-95bd-6895ddce6386.png)

**Comment by djow2019** [comment]
My vote is for Myriad Pro, and the favicon looks great! Also as a side note, Andrew mentioned that you have some pictures of the chlamydia pathogen that you've taken in the lab. Would you like to use one of those as the splash graphic instead?

**Comment by khybiske** [comment]
@djow2019 I can look for something suitable. I have plenty.

**Comment by putmantime** [comment]
Really like the Icons Kevin!  Perfect representation of Chlamydia and its unique life cycle.

**Comment by khybiske** [comment]
Something like this..? I will also need some guidance on what sort of images you guys need, transparent or no, file format, etc. All of my web coding experience is from last century (literally).

![chlambase splash](https://user-images.githubusercontent.com/29986637/39260669-0989498c-486f-11e8-91c1-830f1e8044f5.png)

**Comment by khybiske** [comment]
I am thinking that may be a little 'plain' now that I look at it... It needs something else. I couldn't find a good image that could be spread wide as a background. Can keep hunting...

**Comment by putmantime** [comment]
Love the image and how it fades into black though.  I think the purple and black could work with the blue if we change the color of the 'Take the tour' button to be more in sync with the rest of the palette.  If you have more purple single cell images we could add those across the splash background.  Or maybe just one more, of a different shape on the other side?

Re: format I think just a jpg would work, not sure how we could do a transparent with a photographic image.

**Comment by djow2019** [comment]
I made a quick UI wireframe of the landing page using your v2 graphic. I don't have the original picture you used, so in the real version the upper left corner will be expanded with the transparency effect as you have it above. Tell me what you think.

![image](https://user-images.githubusercontent.com/3160053/39271128-f37b8420-488c-11e8-91d5-82998993bc2a.png)

![image](https://user-images.githubusercontent.com/3160053/39271135-f9f8ae72-488c-11e8-9c6d-5285ad10f52f.png)

![image](https://user-images.githubusercontent.com/3160053/39271349-a887f52e-488d-11e8-972d-695a4da8f39f.png)

Might be too dark.

**Comment by khybiske** [comment]
@djow2019 What can I give you to make implementing that easier? I have the fluorescent banner image, also the ChlamBase text logo. The caption and orange button I assumed would be the text from the current site. I made my mockup in Illustrator, in case you have it for extracting whatever graphics you like.

The black background for the main content is fine. Probably makes more sense than blue.

**Comment by djow2019** [comment]
Just need the individual images - the text logo, the chlam graphic in the upper left, and the favicon icon

**Comment by khybiske** [comment]
[chlambase.zip](https://github.com/SuLab/ChlamBase.org/files/1948847/chlambase.zip)
@djow2019 Everything should be in here. I saved images as .png to preserve transparencies. Also feel free to downscale them if too large.

**Comment by khybiske** [comment]
If you feel black is too dark, maybe a gradient background? Black to ....?  Seems like something that css can do, but I also can't think of any website examples that do that. Maybe for a good reason.

**Comment by djow2019** [comment]
All black wasn't very good, I tried expanding the original banner image as a fill. What do you think?
https://www.dropbox.com/s/pnk4i1mbcj14b4i/screenshot.png?dl=0

**Comment by khybiske** [comment]
@djow2019 I like that. Let me dig up the actual size image tomorrow so you don't have to expand the narrower one – it's on my office computer.

**Comment by khybiske** [comment]
@djow2019 Try this one. You are welcome to scale/crop however you like. No fading on this image, doesn't seem necessary. 

![splash](https://user-images.githubusercontent.com/29986637/39439947-288fbe54-4c5e-11e8-9c51-0b8423f04194.jpg)

**Comment by djow2019** [comment]
Ok, some quick AB Testing here. Heres the original:
![image](https://user-images.githubusercontent.com/3160053/39448573-27691680-4c7a-11e8-9e31-0b4fa4d7039e.png)

Now the same image, but changed to blue to match with the theme:
![image](https://user-images.githubusercontent.com/3160053/39448744-b51abe34-4c7a-11e8-8d0e-23437e6b0958.png)

**Comment by khybiske** [comment]
I like the blue!
