### ISSUE TITLE
UX suggestion

### ISSUE THREAD

**Issue by khybiske** [SuLab/ChlamBase.org#27]
Easy one. Some users have mentioned they don't know what to do from the home page. I might suggest we somehow guide the user to click one of the 4 boxed genomes. e.g. color them, or put a fat arrow to the left of the tree...

**Comment by andrewsu** [comment]
in hipchat discussion, @djow2019 suggested using intro.js for this, which I think sounds great.  I think we'd just need 4 steps to the intro: 1) the four strains, 2) the genome search, 3) the keyword search, and 4) the "what's happening" carousel.

**Comment by khybiske** [comment]
Great idea! But will that script come up each time someone accesses the site, or is it smart enough to know I am a return visitor and keep quiet?

**Comment by djow2019** [comment]
It should only run for first time visitors, so it will only display once.

**Comment by djow2019** [comment]
Here is what the tutorial looks like right now:

![screenshot from 2017-09-30 16-01-51](https://user-images.githubusercontent.com/3160053/31050221-4e6734c4-a5f9-11e7-8f83-901b6286798e.png)
![screenshot from 2017-09-30 16-02-03](https://user-images.githubusercontent.com/3160053/31050223-510679b0-a5f9-11e7-9189-9689c9843375.png)
![screenshot from 2017-09-30 16-02-10](https://user-images.githubusercontent.com/3160053/31050224-53435a7c-a5f9-11e7-821c-751a77726be9.png)
![screenshot from 2017-09-30 16-02-20](https://user-images.githubusercontent.com/3160053/31050225-55092b52-a5f9-11e7-8c58-32c1a19fbece.png)
![screenshot from 2017-09-30 16-02-33](https://user-images.githubusercontent.com/3160053/31050226-5624c924-a5f9-11e7-9dbf-d6f8e65591b3.png)
![screenshot from 2017-09-30 16-02-40](https://user-images.githubusercontent.com/3160053/31050227-57276872-a5f9-11e7-9dae-21a1b3714260.png)

**Comment by andrewsu** [comment]
This looks great! What do people think about having this intro be triggered
after clicking a "get started" button somewhere near the top of the page,
instead of starting by default for first time visitors?

**Comment by djow2019** [comment]
Personally, I would prefer without the button because it saves me a click. But a button at the top might be nice in case someone wants to watch the tutorial again without clearing the cache.

**Comment by khybiske** [comment]
My vote would probably be for a 'get started' button. I like the tutorial feature.
