### ISSUE TITLE
collect data on host cell localization

### ISSUE THREAD

**Issue by andrewsu** [SuLab/ChlamBase.org#34]
doesn't have to be complete, just enough example cases to show in paper.

**Comment by andrewsu** [comment]
kevin will provide a list of genes that localize to inclusion membrane

The list of all possible localizations can come from the SVG -- @putmantime and I need to find closest mappings in GO (and request new terms if necessary)....

**Comment by khybiske** [comment]
Done!  I tabulated all of the relevant genes: [google sheet](https://docs.google.com/spreadsheets/d/1HlLI1EoBGeA2YHu15ZVGVVbycI2cxoTHSY2mzWq1mDw/edit?usp=sharing)

**Comment by andrewsu** [comment]
@khybiske three questions for you...

First, you annotated CT456 / CTL0716 / TC0741 to "actin cytoskeleton".  I just want to confirm that you mean the _chlamydia_ actin cytoskeleton and not the host actin skeleton, correct? 

Second, just to be sure we get it right, can you highlight/describe exactly what should be colored for "inclusion membrane"?  Is it the outer ring of the shaded circles?  Just trying to differentiate it from "EB" component.

![2018-04-02_15-24-13](https://user-images.githubusercontent.com/2635409/38219381-36efe1ca-368a-11e8-9d0e-af8d528da465.png)

Third (and this one might be the toughest), if we are going to add these annotations to Wikidata, then ideally we need a reference to support the localization annotation.  Also we ideally need to know which exact protein was mentioned in the reference (on the assumption that only one of these CT005 / CTL0260 / TC0273 was actually studied, and the other two were inferred based on their sequence similarity).  How difficult would it be to add those to the spreadsheet?  Again, even doing just a handful of cases would be just fine...

**Comment by khybiske** [comment]
@andrewsu 
1. I actually do mean the host actin cytoskeleton (the straw like stuff close to the plasma membrane). I chose this CT example as one that we know is secreted into the host cell. Annotating proteins like this (CT has ~100 of them) is pure magic if we can capture that.

2. Inclusion membrane = the nucleus-size membrane encircling all of the bacteria. I made 2 sizes of bacteria, EB (shaded dots) and RB (larger circles). A 4th compartment would be the white inside of the inclusion. We have some data (from literature, not in NCBI etc) which I can annotate into all 4 of these locations. 

3. Not that difficult actually. If you send along whatever master sheet you'd like me to use, I can easily populate it with 40+ evidence-based examples. Nothing I would annotate would be from pure speculation or prediction.

**Comment by andrewsu** [comment]
great, thanks!

1. I updated the google spreadsheet to say "host actin cytoskeleton".

2. Super, very clear now, thanks.  I think annotating at least one example gene for each of those four compartments would be great actually...

3. Great, let's use the same google sheet that you prepared.  I added two columns for "PMID of supporting paper" and "Specific Gene ID studied in paper".  No need to fill those out for every row in the sheet -- just enough for a representative example.

**Comment by khybiske** [comment]
@andrewsu 'Specific Gene ID' = what exactly? NCBI #?

**Comment by andrewsu** [comment]
@khybiske I would say any of the gene symbols from columns A-C, e.g., CT005, CTL0260, or TC0273.  I changed "gene ID" to "gene symbol" in the header to hopefully make that clearer...

**Comment by khybiske** [comment]
@andrewsu I'll get this done by tomorrow. Is Derek working on the implementation?

**Comment by khybiske** [comment]
@andrewsu Sheet is done!

**Comment by andrewsu** [comment]
looks like we have all the data we need, so closing this issue
