### ISSUE TITLE
oauth authentication not working 

### ISSUE THREAD

**Issue by andrewsu** [SuLab/ChlamBase.org#44]
No response to clicking "Authorize to edit" button in the upper right.  Error message from console: 

![2018-04-03_17-14-35](https://user-images.githubusercontent.com/2635409/38282011-8b37e97a-3762-11e8-8e4c-35152e5f7515.png)

**Comment by djow2019** [comment]
I think the oauth token was overwritten back to empty the last time we pulled from the repo

**Comment by andrewsu** [comment]
@putmantime I think Derek can help debug this one, but I'm not finding a link to a page that describes wikidata's oauth tutorial.  Can you send a pointer please?

**Comment by djow2019** [comment]
We need to configure the callbackURL to use a chlambase.org domain name. The application we use is the wikigenomes one https://meta.wikimedia.org/w/index.php?title=Special:OAuthListConsumers/view/c14cf96fc38ab0ff34352d0996768d9f&name=wikigenomes.org&publisher=&stage=1 which only allows wikigenomes.org callback urls.

**Comment by djow2019** [comment]
updated the consumer key and secret to use chlambase.org application. Currently in proposed status, but the callbackurl is working now and at least redirects you to the login screen. Only the developer has access to login right now, but will work like magic once its accepted

https://meta.wikimedia.org/w/index.php?title=Special:OAuthListConsumers/view/c38063969dd943af4b468be0718b4514&name=Chlambase.org&publisher=&stage=-1

**Comment by djow2019** [comment]
Gonna bump @putmantime          
Consumer Key: c38063969dd943af4b468be0718b4514
More information: https://meta.wikimedia.org/w/index.php?title=Special:OAuthListConsumers/view/c38063969dd943af4b468be0718b4514&name=Chlambase.org&publisher=&stage=-1

**Comment by djow2019** [comment]
After @putmantime contacted Epoch Fail on his wiki page, we got the chlambase application approved and now oauth works for all users.
