### ISSUE TITLE
Several genes show "doesn't seem to be a gene in this genome" on main page

### ISSUE THREAD

**Issue by djow2019** [SuLab/ChlamBase.org#49]
Example: see TC_RS00050 under Muridarum Nigg

**Comment by putmantime** [comment]
It seems that these are genes that have no encoded proteins in wikidata.   Working on a solution now

**Comment by putmantime** [comment]
Looks like the [protein bot](https://github.com/SuLab/scheduled-bots/blob/master/scheduled_bots/geneprotein/ProteinBot.py) is  '# only using items with exactly one swiss-prot or trembl ID'  and the mygene call for TC_RS00050 returns 2 ids in the trembl field. https://mygene.info/v3/gene/1245533 . Will have loop @stuppie in here and think about how to include thes.

**Comment by andrewsu** [comment]
... and to note, this is a link that reproduces the error: http://chlambase.org/organism/243161/gene/TC_RS00070

**Comment by djow2019** [comment]
I modified the query to make the encoding property optional.
![image.png](https://images.zenhubusercontent.com/5a6639ad4b5806bc2bc3ca25/c78a9e17-a763-4671-89a2-ab79b39af1c2)
Now, it properly selects non-coding genes
