### ISSUE TITLE
Localization Visualization module

### ISSUE THREAD

**Issue by putmantime** [SuLab/ChlamBase.org#7]
-graphical visualization of the subcellular localization based on the cellular component go annotation

**Comment by khybiske** [comment]
Something like this? (for an inclusion membrane protein)
<img width="396" alt="screen shot 2017-07-07 at 12 54 22 pm" src="https://user-images.githubusercontent.com/29986637/27974945-0fb06dda-6315-11e7-94a3-b64401fc37a8.png">

**Comment by andrewsu** [comment]
Examples of interactive localization widgets:

* [GDC Data Portal](https://portal.gdc.cancer.gov/)
* [TISSUES](http://tissues.jensenlab.org/Entity?figures=tissues_body_%&knowledge=10&experiments=10&textmining=10&homologs=10&type1=9606&type2=-25&id1=ENSP00000266970)

**Comment by khybiske** [comment]
@andrewsu Have you seen this one? 

http://www.proteinatlas.org/ENSG00000148396-SEC16A/cell

Effective and appropriate, however Tim says we cannot swipe their code. Ultimately, I think if we just make a series of graphics for all of the organelles/locations we could have (tailored to chlamydia infected cells), then the annotation can just trigger a particular one to display. Not hard. I can do images.

**Comment by andrewsu** [comment]
great, I knew I was missing one (at least).  Ideally it would be something more clever than static images -- creating all combinations of expression patterns would be cumbersome.  Anyway, I see this as a nice-to-have, so tagging this as "help wanted" in case we get a enterprising student or intern that needs a project...
