### ISSUE TITLE
wikidata EC Numbers with single digit

### ISSUE THREAD

**Issue by djow2019** [SuLab/ChlamBase.org#70]
This is not a chlambase issue, but I wanted to report the  bug. For certain enzyme classes that have a single digit EC Number, the url is incorrect. See https://www.wikidata.org/wiki/Q14859873 (lyase activity). It links to https://enzyme.expasy.org/EC/4 when it should be https://enzyme.expasy.org/EC/4.-.-.- (padded with hyphens and periods at the end)

@andrewsu

**Comment by andrewsu** [comment]
thanks @djow2019! copied the ticket to another issue in the appropriate repo...
