### ISSUE TITLE
Edit/update Gene names

### ISSUE THREAD

**Issue by khybiske** [SuLab/ChlamBase.org#78]
Users will want to update gene names as they become characterized, e.g. change hypothetical proteins to their evidence-based names. How can we do this? The top panel right below jbrowse does not offer annotation submissions.

**Comment by djow2019** [comment]
@khybiske you should be able to change the gene labels now. Click the edit button next to the gene label, and enter the new gene label with the first letter lowercase. It will also automatically update the name of the protein product with the first letter in uppercase

**Comment by khybiske** [comment]
@djow2019 I just noticed you added that feature. I submitted one for CTL0260 (our example for new features). It is updating...

**Comment by djow2019** [comment]
I see  inclusion membrane protein V CTL0260, correct?

**Comment by khybiske** [comment]
That is a feature we need to be careful with. I wouldn't want users changing gene names willy nilly, or inadvertently. How feasible is it to store or display the previous gene name? And possibly who made the change. As an archive of changes. In this example, it would show 'hypothetical protein', so anyone viewing it would be happy with the change.

**Comment by djow2019** [comment]
The archives are saved in wikidata version history. You can see the history page here
https://www.wikidata.org/w/index.php?title=Q21169165&type=revision&diff=703484837&oldid=703041489

So you can get to this page by clicking the wikidata reference icon, then clicking view history.

Going to ping @andrewsu for thoughts
