### ISSUE TITLE
faceting genes by different data types

### ISSUE THREAD

**Issue by putmantime** [SuLab/ChlamBase.org#8]
Search results can be faceted based on data like expression timing and mutant availability

**Comment by khybiske** [comment]
I would implement it by having expression and mutants open up a window or dropdown that lets the user check which subcriteria they are interested in. For example, I click mutants and check which of the subtypes (chemical-stop, chemical-syn, chemical-nonsyn, transposon, etc) I want. Also a keyword search box.

**Comment by djow2019** [comment]
Is there anything left to do here?

**Comment by khybiske** [comment]
No, I think it's all good
