### ISSUE TITLE
Ortholog module: protein sequences

### ISSUE THREAD

**Issue by khybiske** [SuLab/ChlamBase.org#83]
The DNA alignments are great. Can we do something similar for amino acid sequences? Maybe give users a checkbox to choose which?

**Comment by djow2019** [comment]
I decided to split up the ortholog module into two components: one for the table, one for the alignment. Will probably look something like this:
![image.png](https://images.zenhubusercontent.com/5a6639ad4b5806bc2bc3ca25/dbb60dc5-c18f-44f6-9138-21ecae65fbcf)

**Comment by andrewsu** [comment]
Hmm, I'm of two minds on this reconfiguration.  On the one hand, I think this is great because it raises the visibility of the alignments.  On the other hand, the alignments are specifically of the orthologs and not of other sequences against which one might want to align.  Before @djow2019 gets too deep in implementing this, do either @khybiske or @putmantime have any strong opinions?

**Comment by khybiske** [comment]
@andrewsu Excellent points. What if @djow2019 renamed his new 'Alignment' module as 'Ortholog alignments'? That would almost satisfy both sides of your argument, no? Alternatively, make it a nested submodule of Orthologs. Essentially, remove the blue banner. I am happy with either of these options. Although I am also perfectly happy with all variations of this that I've seen so far. 

I might not call this module, submodule, whichever... as 'Alignment'. It's a little too nondescriptive. I'd prefer 'Ortholog alignments' or 'Sequence alignments'.

**Comment by djow2019** [comment]
Got "Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://www.ncbi.nlm.nih.gov/protein/NP_224891?report=fasta. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing)." Again. Will need to set up another reverse proxy...

**Comment by putmantime** [comment]
+1 on specifying that the alignments are ortholog specific

**Comment by djow2019** [comment]
To fix the domain issue, I just had to use the efetch url. Protein alignments are now working!
![image.png](https://images.zenhubusercontent.com/5a6639ad4b5806bc2bc3ca25/60dc8218-9737-4f5a-95b2-e32b999fbf97)

**Comment by djow2019** [comment]
I should add that in the above image, the muridarum strain did not have a protein coding product so it did not align that sequence.

**Comment by djow2019** [comment]
Cleaned it up
![image.png](https://images.zenhubusercontent.com/5a6639ad4b5806bc2bc3ca25/e0546ecf-9ef2-4739-884c-77acd80a0988)

**Comment by khybiske** [comment]
Very nice! Is this function live now?

**Comment by djow2019** [comment]
Not yet, I'm working on adding the mutant column to the original ortholog table and then I'll make one large push to production after

**Comment by djow2019** [comment]
@khybiske Update is live
