### ISSUE TITLE
Annotate C. muridarum transposon mutants

### ISSUE THREAD

**Issue by khybiske** [SuLab/ChlamBase.org#84]
@putmantime I created a little data table in figshare containing the mutants I would like to annotate in our database. Not clear to me if/when that data gets issued a DOI, or how to reference that in the annotation submission form. ?

**Comment by khybiske** [comment]
@djow2019 This is another issue that needs looking into. I suspect an easy fix based on your solutions to annotation bugs yesterday. Essentially, the site isn't letting me submit transposon mutant annotations. We either need to be able to (A) submit using my figshare DOI (10.6084/m9.figshare.6465173), or (B) submit with no reference. I am happy with either.

**Comment by djow2019** [comment]
@khybiske Can you give me a sample annotation so I can test with it?

**Comment by djow2019** [comment]
I'll add support for figshare DOI

**Comment by khybiske** [comment]
Gene: TC_0206
Strain name: UWCM_001
Type: transposon
Genome position: 242824
Insert direction: forward
% gene left intact: 86

**Comment by djow2019** [comment]
@andrewsu To autocomplete pubmed IDs, we pull data from the NCBI pubmed database. I don't see a database for figshare. Is there an alternative or should we scrap autocomplete?

**Comment by djow2019** [comment]
@khybiske Added the dropdown option for figshare.
I deleted and resubmitted your annotation to add the figshare reference
![image.png](https://images.zenhubusercontent.com/5a6639ad4b5806bc2bc3ca25/4ff2ec79-2a7b-4b01-a19d-64f7b9ad8616)
