### ISSUE TITLE
host pathogen interaction module

### ISSUE THREAD

**Issue by putmantime** [SuLab/ChlamBase.org#9]
Identify other bacterial genes that interact with the same host entity.
Effectors etc.

**Comment by putmantime** [comment]
Identify host pathogen database resources 
(e.g. http://www.agbase.msstate.edu/, http://eupathdb.org/eupathdb/)

**Comment by khybiske** [comment]
Here are some actual examples to use for piloting. 
[HPI chlambase.xlsx](https://github.com/SuLab/ChlamBase.org/files/1132321/HPI.chlambase.xlsx)

In implementation, I'd love if **evidence** was filterable. There are some Incs, e.g., from the 26118995 proteomics dataset, that have dozens of host 'targets'. Many of these are probably not accurate, but for now it's all we have. As a user, I'd like the option of filtering the evidence/confidence level by checkboxes or similar (proteomics would be lower confidence).

**Comment by khybiske** [comment]
The host protein target is the real action item of this module. At its simplest, it could/should link out to a richer db entry (wikipedia, UP, whatever). But even better, the module could alert the user, or allow the user to query if any entries in wikigenomes also interact with this target.

**Comment by putmantime** [comment]
To start with, I modeled the first pathogen-host interaction in the table you provided in Wikidata
https://www.wikidata.org/wiki/Q21168208  Seems like all the pieces are already in place and these are published claims so they might as well go in WD if this looks good.

**Comment by khybiske** [comment]
That does look good, on the wikidata end. It just occurred to me that this example probably used L2 experimentally, even though these authors may discuss IncD as CT115 (we are all guilty of that). This brings up a question about how rigidly we annotate an interaction for a given Chlamydia strain. As you know, labs rarely check findings for other strains, and we pretty much _expect_ that molecular findings will extend to other strains...

**Comment by khybiske** [comment]
I don't have a good solution. One idea might be to classify an interaction entry as **established** (for the ones used in the references), or **predicted** (for orthologs).

**Comment by putmantime** [comment]
Oh.  Then this comes down to that one sentence in so many C. trachomatis papers "We have translated to  the DUW3"  Locus tags.

I think your right that the claim should be made on the strain that was experimented on then any orhtologs should be qualified as predicted or something like that

**Comment by khybiske** [comment]
I'm on board with that.

**Comment by putmantime** [comment]
Here is an prototype model of the first entry (incD) of https://github.com/SuLab/ChlamBase.org/files/1132321/HPI.chlambase.xlsx in Wikidata. 
As discussed in the issue thread, the L2 strain is the one that was actually experimented on so I created the claim on  L2/434/bu https://www.wikidata.org/wiki/Q21172774
with the ‘determination method’ qualifiers co-localization evidence (Q32860432) and immunoprecipitation evidence (Q32860428)(both new items created from ECO terms).

The claim has also been added to the more commonly referenced ortholog D/UW-3/CX https://www.wikidata.org/wiki/Q21168208 using the ‘determination method’ qualifier sequence orthology evidence (Q32909829).

Any thoughts on this model would help.  Since these are published claims I thought it would be most appropriate for these to go directly to Wikidata.  Might be a logical next annotation form for chlambase as well.

**Comment by stuppie** [comment]
To restate discussion from meeting:
1) Link the two genes as orthologs. Unless there is another primary source for this, the reference would be you/Tim Putman/Wikigenomes.org ? The interacting proteins could be queried explicitly through orthologs.
2) If you annotate the other gene using the 'determination method' 'sequence orthology evidence', you should include the ortholog as part of the claim (somehow). Example of how that looks in GO [here](http://www.ebi.ac.uk/QuickGO/GAnnotation?protein=P12345) (the "With" column). *You*/Tim Putman/Wikigenomes.org then also would be the "curator" for this annotation as well.

**Comment by djow2019** [comment]
Since we have the host pathogen interaction module, is there anything left to do?
