### ISSUE TITLE
Add annotations to multiple gene orthologs

### ISSUE THREAD

**Issue by khybiske** [SuLab/ChlamBase.org#91]
Let's make it easy to spread new annotation data to relevant gene orthologs. Somewhere in each annotation submission form, ask the user to check boxes for other orthologs to copy the annotation to.  Should be unchecked by default, to avoid inadvertent copying. Maybe also on the final 'review annotation submission' view, make it clear to the user that they will be writing the annotation to additional strains.

**Comment by khybiske** [comment]
@djow2019 I was just thinking about this feature/issue. It isn't urgent, but sure would be nice to have before I proceed with annotating a bunch of genes. If easy to implement, then 'urgent'. 😁

**Comment by djow2019** [comment]
@khybiske Which forms? Just GO annotations? HP?

**Comment by khybiske** [comment]
I would say every one except mutants. Gene name too (the one you created the other day).

**Comment by khybiske** [comment]
This is a good example, since I/you changed the gene name for CTL0260, but that should be pushed to CT_005 as well. I meant to change it for that ortholog but forgot to.

**Comment by djow2019** [comment]
Ok. I can make it work for all of them except the operon form. That might have to be done individually...

**Comment by khybiske** [comment]
No problem. Operon is the least important, since we don't have operon data for 99% of the genes.

**Comment by djow2019** [comment]
@khybiske Multiple ortholog option now live for GO annotations only

**Comment by djow2019** [comment]
HP Interactions with orthologs now done

**Comment by djow2019** [comment]
@khybiske All done! You can now select which genes to apply the annotations to for the gene name form, GO forms, and HP form. I reset CTL0260 back to hypothetical protein so you can confirm that the feature works.
