### ISSUE TITLE
Crash on adding Host Pathogen Annotation

### ISSUE THREAD

**Issue by djow2019** [SuLab/ChlamBase.org#96]

**Comment by djow2019** [comment]
Found the exact line causing the crash.
![image.png](https://images.zenhubusercontent.com/5a6639ad4b5806bc2bc3ca25/9ac74fc0-1ece-4327-8179-448680857aa4)

Output with print statements:
![image.png](https://images.zenhubusercontent.com/5a6639ad4b5806bc2bc3ca25/fcc27cc3-7e91-47f7-beb4-f95ad0e4bf8b)

**Comment by djow2019** [comment]
Specifically, passing the parameter "wd_item_id=..." causes it to become unresponsive. Tried setting a hard value like so:

wd_item_protein = wdi_core.WDItemEngine(wd_item_id='Q21168345')

But it also crashed the server

@putmantime @andrewsu Thoughts?

**Comment by djow2019** [comment]
Problem with outdated wdi. Going to update it now.

**Comment by djow2019** [comment]
HP now works, going to check with other annotations.

**Comment by djow2019** [comment]
@khybiske when you get a chance, can you try resubmitting the annotation in the host pathogen interactions module? I believe it is fixed...

**Comment by khybiske** [comment]
@djow2019 I just submitted one for CTL0260 and it said I was successful. Let's see if it updates.
